config_version = 4
enable_system_global_packs = false
log_pack_ids = false

[resourcepacks]
required = ["config/cobbleverse"]
enable_builtin = []

[datapacks]
required = ["datapacks/"]
optional = ["datapacks/extra/"]
enable_builtin = []
